// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.HashGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("input_text")]
        public string InputText { get; set; }

        [JsonProperty("input_length")]
        public long InputLength { get; set; }

        [JsonProperty("algorithms_used")]
        public string[] AlgorithmsUsed { get; set; }

        [JsonProperty("hashes")]
        public Hashes Hashes { get; set; }

        [JsonProperty("hash_details")]
        public HashDetail[] HashDetails { get; set; }

        [JsonProperty("available_algorithms")]
        public string[] AvailableAlgorithms { get; set; }
    }

    public partial class HashDetail
    {
        [JsonProperty("algorithm")]
        public string Algorithm { get; set; }

        [JsonProperty("hash")]
        public string Hash { get; set; }

        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("uppercase")]
        public string Uppercase { get; set; }
    }

    public partial class Hashes
    {
        [JsonProperty("sha256")]
        public string Sha256 { get; set; }

        [JsonProperty("md5")]
        public string Md5 { get; set; }
    }
}
